POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNAZ21haWwuY29tIiwiZXhwIjoxNzE5MDgwNzQ5LCJ1c2VySWQiOjF9.jYPMxJqH4I3dqyhbsPudnJ6o6ygg-tK4FFs1aKkw5YU

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}
