PUT http://localhost:8080/events/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAZ21haWwuY29tIiwiZXhwIjoxNzE5MDc1NzUxLCJ1c2VySWQiOjJ9.6nFZAQJ754Swa_1WBOhovuHwlDO_T8bFM4goCLx8UrI

{
    "name": "Test event updated",
    "description": "A test event",
    "location": "Test location(updated)",
    "dateTime": "2025-01-01T15:30:00.000Z"
}